# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_demo_documentation',
                'doc_host': 'https://surenoobster.github.io',
                'git_url': 'https://github.com/surenoobster/nbdev_demo_documentation',
                'lib_path': 'nbdev_demo_documentation'},
  'syms': {'nbdev_demo_documentation.core': {'nbdev_demo_documentation.core.foo': ('core.html#foo', 'nbdev_demo_documentation/core.py')}}}
